import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
=======
>>>>>>> 811a251cfe6b950a5784c042bb0d3e805c7e5d0d

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <ClerkProvider>
      <html lang="en">
        <body>
          <Header />
          <div className=" flex min-h-screen">
            {/* {sidebar} */}
             <Sidebar/>
            <div className="flex-1 p-4 bg-gray-100">{children}</div>
          </div>
        </body>
      </html>
    </ClerkProvider>
=======
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
>>>>>>> 811a251cfe6b950a5784c042bb0d3e805c7e5d0d
  );
}
